
                </table>
              </div>
            </div>
          </td>
          <td class="right">
            <div class="main-subcontent" id="content_bar">
              <div id="panel_default">
                <div class="subcontent-unit-border-orange">
                  <div class="round-border-topleft"></div>
                  <div class="round-border-topright"></div>
                  <h1 class="orange">Browse...</h1>
                  <ul>
                    <li><a href="/agent/list.html">Resource&nbsp;Owners</a>
                    </li>
                    <li>
                      <a href="/vocabulary/list.html">Vocabularies</a>
                    </li>
                    <li>
                      <a href="/schema/list.html">Schemas</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div id="gplus" style= "width:170px; text-align: left; margin-left: 20px; margin-top: -20px ">
              <g:plusone size="medium"></g:plusone>

              <script type="text/javascript">
                (function() {
                  var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                  po.src = 'https://apis.google.com/js/plusone.js';
                  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                })();
              </script>
              </div>
            <div id="tweet" style= "width:170px; text-align: left; margin-left: 20px; margin-top: 10px;">
            <a href="http://twitter.com/share" class="twitter-share-button" data-text="RDA RDF Vocabularies!" data-count="horizontal" data-via="jonphipps" data-related="RDAVocabs:RDA Vocabularies">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
            </div>
            <div id="facebook" style= "width:170px; text-align: left; margin-left: 20px; margin-top: 10px;">
<div id="fb-root"></div>
<script>(function(d){
  var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
  js = d.createElement('script'); js.id = id; js.async = true;
  js.src = "//connect.facebook.net/en_US/all.js#appId=217675834954665&xfbml=1";
  d.getElementsByTagName('head')[0].appendChild(js);
}(document));</script>
<div class="fb-like" data-href="http://rdvocab.info" data-send="false" data-layout="box_count" data-width="140" data-show-faces="false" data-font="tahoma"></div>
            </div>
          </td>
        </tr>
      </table>
    </div>
    <div id="footer">
      <a href="http://creativecommons.org/licenses/by-nc-sa/3.0/" rel="license"><img alt="Creative Commons License" src="http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png" style="border-width:0" /></a> powered by <a href="http://www.symfony-project.com/"><img align="middle" alt="Symfony" src="images/symfony.gif" /></a>
    </div>
<script type="text/javascript" charset="utf-8">
  var is_ssl = ("https:" == document.location.protocol);
  var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
  document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<script type="text/javascript" charset="utf-8">
  var feedback_widget_options = {};

  feedback_widget_options.display = "overlay";  
  feedback_widget_options.company = "managemetadata";
  feedback_widget_options.placement = "right";
  feedback_widget_options.color = "#D8732F";
  feedback_widget_options.style = "idea";
  
  
  
  
  
  
  

  var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
</script>  </body>
</html>
