
                </table>
              </div>
            </div>
          </td>
          <td class="right">
            <div class="main-subcontent" id="content_bar">
              <div id="panel_default">
                <div class="subcontent-unit-border-orange">
                  <div class="round-border-topleft"></div>
                  <div class="round-border-topright"></div>
                  <h1 class="orange">Browse...</h1>
                  <ul>
                    <li><a href="/agent/list.html">Resource&nbsp;Owners</a>
                    </li>
                    <li>
                      <a href="/vocabulary/list.html">Vocabularies</a>
                    </li>
                    <li>
                      <a href="/schema/list.html">Schemas</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </td>
        </tr>
      </table>
    </div>
    <div id="footer">
      <a href="http://creativecommons.org/licenses/by-nc-sa/3.0/" rel="license"><img alt="Creative Commons License" src="http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png" style="border-width:0" /></a> powered by <a href="http://www.symfony-project.com/"><img align="middle" alt="Symfony" src="images/symfony.gif" /></a>
    </div>
<script type="text/javascript" charset="utf-8">
  var is_ssl = ("https:" == document.location.protocol);
  var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
  document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript" charset="utf-8">
  var feedback_widget_options = {};
  feedback_widget_options.display = "overlay";  
  feedback_widget_options.company = "managemetadata";
  feedback_widget_options.placement = "right";
  feedback_widget_options.color = "#D8732F";
  feedback_widget_options.style = "idea";
  var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
</script>  </body>
</html>
