<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" itemscope itemtype="http://schema.org/Product">
  <head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <meta content="text/css" http-equiv="Content-Style-Type" />
    <meta content="The Registry! :: FRBR Vocabularies" name="title" />
    <meta content="index,follow" name="robots" />
    <meta content="The Open Metadata Registry Project FRBR Vocabularies" name="description" />
    <meta content="semantic web, registry, rdf, skos, metadata, FRBR" name="keywords" />
    <meta content="en" name="language" />
    <meta itemprop="name" content="FRBR Elements and Vocabularies" />
    <meta itemprop="description" content="Properties and concepts from FRBR, available in human-readable and machine readable forms with URIs" />

    <title>The Registry! :: FRBR</title>
    <link href="registry_favicon_beta.ico" rel="shortcut icon" />
    <link href="http://metadataregistry.org/blog/category/registry-development/the-registry/feed/rdf" rel="alternate" title="Registry News RSS 1.0 (RDF)" type="application/rss+xml" />
    <link href="http://metadataregistry.org/blog/category/registry-development/the-registry/feed" rel="alternate" title="Registry News RSS 2.0" type="application/rss+xml" />
    <link href="http://metadataregistry.org/blog/category/registry-development/the-registry/feed/atom" rel="alternate" title="Registry News Atom 1.0" type="application/atom+xml" />
		<link href="css/main.css" media="screen" rel="stylesheet" type="text/css" />
		<link href="css/layout.css" media="screen" rel="stylesheet" type="text/css" />
 <script type="text/javascript">

</script>
  </head>
  <body>
    <div id="indicator" style="display: none"></div>
    <div id="header">
      <ul>
        <li><a href="http://metadataregistry.org/login.html">sign in / register</a></li>
        <li class="last"><a href="http://metadataregistry.org/about.html">about</a></li>
      </ul>
      <div style="padding-left: 10px;">
				<a href="http://metadataregistry.org/"><img align="left" alt="registry" src="images/open_metadata_logo_with_interoperability.png" /></a>
      </div>
      <div id="search">
        <table>
          <tr>
            <form action="http://metadataregistry.org/conceptprop/search" method="get">
              <td><input class="searchterm" id="concept_term" name="concept_term" type="text" value="" /></td><td align="left"><input class="small" name="commit" type="submit" value="Search Vocabularies" /></td>
            </form>
          </tr>
          <tr>
            <form action="http://metadataregistry.org/schemaprop/search" method="get">
              <td><input class="searchterm" id="sq" name="sq" type="text" value="" /></td><td align="left"><input class="small" name="commit" type="submit" value="Search Element Sets" /></td>
            </form>
          </tr>
        </table>
      </div>
    </div>
    <div id="content">
      <table class="layout">
        <tr>
          <td class="left">
            <div class="Left" id="content_main">
              <div id="home" style="margin-left:auto;margin-right:auto;">
                <h1>The FRBR Vocabularies</h1> 
				This page provides quick links for the Registered FRBR Element Sets and Value Vocabularies. <br />
				Each set of elements or vocabulary concepts has a link to the general description as well as a link to a list of elements or concepts. 
				<table border="0" cellpadding="0" cellspacing="3">
                  <tr>
                    <td colspan="6"><h3 style="margin-top:10px; padding: 0;">FRBR Element Sets</h3></td>
                  </tr>
